[package]
name = "typeck"
version = "0.1.0"
authors = ["Andy Yu <andyyu2004@gmail.com>"]
edition = "2018"

[dependencies]
span = { path = "../span" }
ir = { path = "../ir" }
lcore = { path = "../lcore" }
ast = { path = "../ast" }
error = { path = "../error" }
infer = { path = "../infer" }
tir = { path = "../tir" }
rustc-hash = "1"
itertools = "0.9"
log = "0.4.11"
