[package]
name = "vm"
version = "0.1.0"
authors = ["Andy Yu <andyyu2004@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "libvm"
path = "src/lib.rs"

[[bin]]
name = "vm"
path = "src/bin.rs"

[dependencies]
clap = { version = "3.0.0-beta.1", features=["yaml"] }
log = "0.4.8"
simple-logging = "2.0.2"
vm-derive = { path = "../vm-derive" }
maplit = "1"
once_cell = "1.4"
rustyline = "6.2"
ena = "0.14"
derive_deref = "1.1"
num_enum = "0.5.0"
itertools = "0.9.0"
thiserror = "1"
rustc-hash = "1.1.0"
scoped-tls = "1"
unicode-xid = "0.2.1"
smallvec = "1.4.0"
indexed_vec = "1.2.1"
lazy_static = "1.4.0"
