stages:
  - build

before_script:
  - apt-get update -yq
  - apt install lsb-release wget software-properties-common -y
  - wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && ./llvm.sh 10
  # - apt-get update -yq && apt-get install llvm llvm-10 llvm-10-dev -y

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
