stages:
  - build

before_script:
  - bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
  # - apt-get update -yq && apt-get install llvm llvm-10 llvm-10-dev -y

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
