[workspace]
members = [
    "src/l",
    "src/infer",
    "src/macros",
    "src/ldriver",
    "src/span",
    "src/lex",
    "src/parse",
    "src/ast",
    "src/lcore",
    "src/ir",
    "src/arena",
    "src/error",
    "src/index",
    "src/util",
    "src/session",
    "src/resolve",
    "src/astlowering",
    "src/typeck",
    "src/tir",
    "src/mir",
    "src/llvm",
]


