[package]
name = "vm"
version = "0.1.0"
authors = ["Andy Yu <andyyu2004@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "libvm"
path = "src/lib.rs"

[[bin]]
name = "vm"
path = "src/bin.rs"

[dependencies]
rustyline = "6.2"
num_enum = "0.5.0"
thiserror = "1"
rustc-hash = "1.1.0"
unicode-xid = "0.2.1"
rustc-ap-arena = "662.0.0"
