version = "Two"
empty_item_single_line = false
reorder_impl_items = true
imports_layout = "Horizontal"
merge_imports = false
max_width = 100
enum_discrim_align_threshold = 10
use_small_heuristics = "Max"
merge_derives = false
single_line_if_else = true
match_arm_blocks = false
