[package]
name = "vm-derive"
version = "0.1.0"
authors = ["Andy Yu <andyyu2004@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
synstructure = "0.12.4"
syn = { version = "1", features = ["full"] }
proc-macro2 = "1"
quote = "1"
