[package]
name = "tir"
version = "0.1.0"
authors = ["Andy Yu <andyyu2004@gmail.com>"]
edition = "2018"

[dependencies]
ir = { path = "../ir" }
ast = { path = "../ast" }
span = { path = "../span" }
index = { path = "../index" }
lutil = { path = "../lutil" }
lcore = { path = "../lcore" }
smallvec = "1.4.2"
log = "0.4.11"
itertools = "0.9"
rustc-hash = "1"
