[package]
name = "ldriver"
version = "0.1.0"
authors = ["Andy Yu <andyyu2004@gmail.com>"]
edition = "2018"

[dependencies]
span = { path = "../span" }
lex = { path = "../lex" }
parse = { path = "../parse" }
ast = { path = "../ast" }
session = { path = "../session" }
error = { path = "../error" }
clap = { version = "3.0.0-beta.1", features=["yaml"] }
colour = "0.5"
