[package]
name = "span"
version = "0.1.0"
authors = ["Andy Yu <andyyu2004@gmail.com>"]
edition = "2018"

[dependencies]
arena = { path = "../arena" }
macros = { path = "../macros" }
rustc-hash = "1.1.0"
codespan = "0.9.5"
codespan-reporting = "0.9.5"
