[package]
name = "lc-session"
version = "0.1.0"
authors = ["Andy Yu <andyyu2004@gmail.com>"]
edition = "2018"

[dependencies]
lc-error = { path = "../lc-error" }
log = "0.4.11"
clap = "3.0.0-beta.2"
serde = { version = "1", features = ["derive"] }
